POST http://localhost:8000/todo
Content-Type: application/json

{
  "todo": "some todo",
  "dueDate": "2023-05-02",
  "location": "Hungary"
}

###

GET http://localhost:8000/todos
Accept: application/json

###

DELETE http://localhost:8000/todo/7e7891bd-3ccb-45c7-b0ab-51e7ded01d71

###

GET http://localhost:8000/todo/7b6f52ca-1b97-4f9c-a80b-a145b5b5cc4b
Accept: application/json