POST http://localhost:8000/todo
Content-Type: application/json

{
  "todo": "some todo",
  "dueDate": "2023-05-02",
  "location": "Hungary"
}

###

GET http://localhost:8000/todos

###

DELETE http://localhost:8000/todo/dc3fb6c2-c57f-492f-b76d-75c78c8afdb3